apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - name: grafana
              containerPort: 3000
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: GF_SMTP_ENABLED
              value: "true"
            - name: GF_SMTP_HOST
              value: "smtp.office365.com:587"
            - name: GF_SMTP_PORT
              value: "587"
            - name: GF_SMTP_USER
              value: "shanmugha13@outlook.com"
            - name: GF_SMTP_PASSWORD
              value: "Shanu@13@outlook"
            - name: GF_SMTP_FROM_ADDRESS
              value: "shanmugha13@outlook.com"
            - name: GF_SMTP_FROM_NAME
              value: "Grafana"
            - name: GF_SMTP_STARTTLS_POLICY
              value: "OpportunisticStartTLS"
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
              readOnly: false
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources

