apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  selector:
    app: kube-state-metrics
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080

